image: docker:latest
stages:      
  - build
  - deploy

services:
  - docker:dind

variables: 
  MANAGER_HOST: "84.201.156.181"
  FILE_VAR: $PREDICTION_CONFIG

build-job:
  stage: build

  rules:
    - changes:
        - "**/*"
  before_script: 
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$SSH_PRIVATE_KEY")

    - ssh olipandrei@${MANAGER_HOST} "docker stop registry"
    - ssh olipandrei@${MANAGER_HOST} "docker rm registry"
    #- ssh olipandrei@${MANAGER_HOST} "docker system prune -a --volumes"
    - ssh olipandrei@${MANAGER_HOST} "docker run -d -p 4000:5000 --restart=always --name registry registry:2"

  script:
    - echo "build job start!"

    - echo "scp start" 
    - scp -prq ynyt/. olipandrei@${MANAGER_HOST}:/home/olipandrei/ynyt
    - scp -prq prediction/. olipandrei@${MANAGER_HOST}:/home/olipandrei/prediction
    - scp -prq artifacts/. olipandrei@${MANAGER_HOST}:/home/olipandrei/artifacts
    - scp -prq dashboard/. olipandrei@${MANAGER_HOST}:/home/olipandrei/dashboard
    - scp -prq data/. olipandrei@${MANAGER_HOST}:/home/olipandrei/data
    - scp -r config.json  olipandrei@${MANAGER_HOST}:/home/olipandrei/config.json
    - scp -prq updater/. olipandrei@${MANAGER_HOST}:/home/olipandrei/updater


    - echo "dashboard-img start"

    - docker build -t ynyt_app -f ./dashboard/Dockerfile .
    - docker tag ynyt_app:latest ${MANAGER_HOST}:4000/ynyt_app:latest
    - docker push ${MANAGER_HOST}:4000/ynyt_app:latest

  #  - ssh olipandrei@${MANAGER_HOST} "docker build -t ynyt_app -f ./dashboard/Dockerfile ."
  #  - ssh olipandrei@${MANAGER_HOST} "docker tag ynyt_app:latest ${MANAGER_HOST}:4000/ynyt_app:latest"
  #  - ssh olipandrei@${MANAGER_HOST} "docker push ${MANAGER_HOST}:4000/ynyt_app:latest"

    - echo "updater-img start"
    - ssh olipandrei@${MANAGER_HOST} "docker build -t ynyt_updater -f ./updater/Dockerfile ."
   # - ssh olipandrei@${MANAGER_HOST} "docker tag ynyt_updater:latest ${MANAGER_HOST}:4000/ynyt_updater:latest"
   # - ssh olipandrei@${MANAGER_HOST} "docker push ${MANAGER_HOST}:4000/ynyt_updater:latest"

    - echo "predict-img start"
    - ssh olipandrei@${MANAGER_HOST} "docker build -t ynyt_prediction -f ./prediction/Dockerfile ."
   # - ssh olipandrei@${MANAGER_HOST} "docker tag ynyt_prediction:latest ${MANAGER_HOST}:4000/ynyt_prediction:latest"
   # - ssh olipandrei@${MANAGER_HOST} "docker push ${MANAGER_HOST}:4000/ynyt_prediction:latest"

    - echo "predict-cron-img start"
    - ssh olipandrei@${MANAGER_HOST} "docker build -t ynyt_prediction_cron -f ./prediction/Dockerfile.cron ."
   # - ssh olipandrei@${MANAGER_HOST} "docker tag ynyt_prediction_cron:latest ${MANAGER_HOST}:4000/ynyt_prediction_cron:latest"
   # - ssh olipandrei@${MANAGER_HOST} "docker push ${MANAGER_HOST}:4000/ynyt_prediction_cron:latest"

    - echo "build job complete!"
  after_script:
    - ssh -T olipandrei@${MANAGER_HOST} "rm -r /home/olipandrei/ynyt"
    - ssh -T olipandrei@${MANAGER_HOST} "rm -r /home/olipandrei/prediction"

app_dashboard:     
  stage: deploy

  before_script: 
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    
    - scp -r app_stack.yml  olipandrei@${MANAGER_HOST}:/home/olipandrei/app_stack.yml
    - echo "MANAGER_HOST=${MANAGER_HOST}" >> .env
    - scp -r .env  olipandrei@${MANAGER_HOST}:/home/olipandrei/.env

  script:
    - echo "Deploying app_dashboard..."
    - ssh olipandrei@${MANAGER_HOST} "docker stack deploy -c ./app_stack.yml app_ynyt"
    - ssh olipandrei@${MANAGER_HOST} "docker service update --replicas 4 app_ynyt"

    - echo "Prediction app_dashboard successfully deployed!"
  
  after_script:
    - ssh -T olipandrei@${MANAGER_HOST} "rm /home/olipandrei/app_stack.yml"
    - ssh -T olipandrei@${MANAGER_HOST} "rm /home/olipandrei/.env"

predictions-update:
  stage: deploy

  before_script: 
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$SSH_PRIVATE_KEY")

    - scp -r prediction_stack.yml olipandrei@${MANAGER_HOST}:/home/olipandrei/prediction_stack.yml
    - cat $FILE_VAR >> /builds/olip78/ynyt.tmp/.env
    - scp -r /builds/olip78/ynyt.tmp/.env olipandrei@${MANAGER_HOST}:/home/olipandrei/.env
    
    - ssh olipandrei@${MANAGER_HOST} "export MANAGER_HOST=${MANAGER_HOST}"

  script:
    - echo "Deploying predict ..."
    - ssh olipandrei@${MANAGER_HOST} "docker run --name prediction --env-file .env --rm -d ${MANAGER_HOST}:4000/ynyt_prediction"
    - ssh olipandrei@${MANAGER_HOST} "docker stack deploy -c ./prediction_stack.yml ynyt_prediction_cron"
    - ssh olipandrei@${MANAGER_HOST} "docker service update --replicas 1 predictions_ynyt"
    - echo "Prediction app successfully deployed!"

  after_script:
    - ssh -T olipandrei@${MANAGER_HOST} "rm /home/olipandrei/.env"
    - ssh -T olipandrei@${MANAGER_HOST} "rm /home/olipandrei/prediction_stack.yml"

