version: "3.9"

services:
  updater:
    image: "${MANAGER_HOST}:4000/ynyt_updater:latest"
    container_name: updater
    logging:
      driver: journald
      options:
        tag: updater
    volumes:
      - app_data:/usr/src/results
    ports:
      - "8081:8081"
    networks:
        - backend

  dashboard:
    image: "${MANAGER_HOST}:4000/ynyt_app:latest"
    container_name: dashboard
    logging:
      driver: journald
      options:
        tag: dashboard
    volumes:
      - app_data:/usr/src/results
    ports:
      - "8080:8080"
    networks:
      - backend
      - frontend

  prediction_cron:
    image: ${MANAGER_HOST}:4000/ynyt_prediction_cron:latest
    container_name: prediction_cron
    env_file:
      - ./.env
    depends_on:
      - updater

volumes:
  app_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge