version: "3.9"

services:
  updater:
    image: "${MANAGER_HOST}:4000/ynyt_updater:latest"
    logging:
      driver: journald
      options:
        tag: updater
    volumes:
      - app_data:/usr/src/results
    ports:
      - "8081:8081"

  dashboard:
    image: "${MANAGER_HOST}:4000/ynyt_app:latest"
    logging:
      driver: journald
      options:
        tag: dashboard
    volumes:
      - app_data:/usr/src/results
    ports:
      - "8080:8080"

services:
  prediction_cron:
    image: ${MANAGER_HOST}:4000/ynyt_prediction_cron:latest
    env_file:
      - ./.env

volumes:
  app_data: